# Generated by Django 3.0 on 2019-12-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
